### ISSUE TITLE
New login dashboard is broken

### ISSUE THREAD

**Issue by arielm-cloudbuzz** [pyro2927/AWS_SSO_Containers#12]
We cannot use this extension with the new aws sso dashboard.
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/110726427/1d092ab0-638d-49ae-96c2-15a562845e92)

**Comment by pyro2927** [comment]
@arielm-cloudbuzz do you have more information as to how to get to the new portal? I am not getting it on my company SSO portal.

**Comment by arielm-cloudbuzz** [comment]
@pyro2927 I am not so sure myself, but apparently when you provision a new sso portal it automatically shows up... it will probably roll-out to all portals later on

**Comment by renshj** [comment]
my Org just rolled over to the new login page, this has broken the extension

**Comment by CraigFosterEH** [comment]
Can confirm the profile login:
`https://{redacted}.awsapps.com/start/#/console?account_id={number redacted}&role_name=Common-PowerUserAccess&referrer=accessPortal` sits there spinning it's circle, then returns after ~ 60 secs with

`https://{redacted}.awsapps.com/start/undefined?Action=login&SigninToken=undefined&Issuer=%2523%252Fconsole%253Faccount_id%253D{number redacted}%2526role_name%253DCommon-PowerUserAccess%2526destination%253Dhttps%25253A%25252F%25252Fconsole.aws.amazon.com&Destination=https%3A%2F%2Fconsole.aws.amazon.com` 

![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/131952411/e8896d7e-80f6-4308-b5da-5c298820c68b)

Disable this extension leaving Containers running, and it proceeds as expected.

**Comment by RhysRedbearIT** [comment]
+1 , exactly same as above, disabled for the moment

**Comment by jem-richards-rbit** [comment]
Same here, had to disable the extension for the new SSO portal

**Comment by Chemsmith** [comment]
Given the sudden influx of people commenting it looks like AWS might have moved the new page to GA. @pyro2927 do you have access to it now?

**Comment by slinkymanbyday** [comment]
Looking at the requests, we may not be able to get account name anymore (at least not as easily), which is quite unfortunate for naming of the containers.

**Comment by pyro2927** [comment]
@Chemsmith unfortunately I do not have the new dashboard. That said the PR from @slinkymanbyday still works for me (old dashboard), and if this is already broken the new dashboard I see no harm in pushing an update that others say have worked for them. Going to push an update to Mozilla shortly and hopefully it resolves all issues folks are seeing.

**Comment by manu-remsense** [comment]
Hi I randomly got the new AWS dashboard as well, and hence I started having the same issues as others. 

I love this plugin, but I disabled it for now.

**Comment by manu-remsense** [comment]
Actually I updated the plugin, given the new PR from @slinkymanbyday and it works perfectly, thanks!

**Comment by CraigFosterEH** [comment]
If users are still seeing this issue, please update to at least v1.6, as available from addons.mozilla.org.

**Comment by renshj** [comment]
> my Org just rolled over to the new login page, this has broken the extension

this has  now been resolved on v1.6 as per Craigs comment.

**Comment by davidebonavita** [comment]
Hi there, it looks like it's now broken for us, as in the plugin is not able to read the account name? I've tried using other variables (email, number, etc) in the extension options, but it always shows the following as container name:

![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/11682646/223dd8f4-9359-41d2-a32b-f61f385914e3)

I'm using the links generated in our AWS Org start page: 
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/11682646/2ba1c9cc-01a0-495f-9090-d84d21a6b99f)

**Comment by cjallen88** [comment]
Same issue here.

**Comment by cjallen88** [comment]
Are the remaining issues in this thread fixed by #20?

**Comment by lohrm-stabl** [comment]
@cjallen88 no, I still have the issue that "name" is not replaced with the actual name in 1.9

**Comment by pyro2927** [comment]
@davidebonavita / @lohrm-stabl  are you still seeing issues? Some changes were made to fix a race condition in the loading of container names.
